[colors.primary]
background = "#040c16"
foreground = "#cce9ea"

[colors.cursor]
text = "#c2cae2"
cursor = "#d9d7d6"

[colors.bright]
black = "#17252A"
red = "#E6676B"
green = "#A2E4B8"
yellow = "#e2d06a"
blue = "#92bbed"
magenta = "#ecc6e8"
cyan = "#80ffff"
white = "#cfebec"

[colors.normal]
black = "#1b2c31"
red = "#FF7377"
green = "#AAF0C1"
yellow = "#eadd94"
blue = "#bdd6f4"
magenta = "#f9ecf7"
cyan = "#b3ffff"
white = "#edf7f8"

[window.padding]
x = 12
y = 12

[font]
size = 10

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[cursor]
style = "Underline"
vi_mode_style = "Underline"
